ews/urls.py
from django.urls import path
from . import views


app_name = "ews"
urlpatterns=[
# List Views
path("bathingspots", views.bathingspots, name="bathing_spots"),
path("sites", views.sites, name="sites"),
path("", views.mlmodels, name="mlmodels"),

#authorization
#path("login", views.login_view, name="login"),
#path("logout", views.logout_view, name="logout"),
path("register", views.register, name="register"),

# create views
path("spot_create", views.spot_create, name="spot_create"),
path("model_config", views.model_config, name="model_config"),
path("model_delete/<int:model_id>", views.delete_model, name="delete_model"),
path("model_edit/<int:model_id>", views.model_edit, name="model_edit"),

path("add_site", views.add_site, name="add_site"),
path("delete_site/<int:site_id>", views.delete_site, name="delete_site"),
path("site_detail/<int:site_id>", views.site_detail, name="site_detail"),

path("selectarea_create", views.selectarea_create, name="selectarea_create"),
# ??
path("detail/<int:spot_id>", views.detail_view, name = "detail"),
path("file_upload/<int:site_id>", views.file_upload, name="file_upload"),
path('model_fit/<int:model_id>', views.model_fit, name ='model_fit'),
path('prediction_switch/<int:model_id>', views.prediction_switch, name ='prediction_switch')
]

plattform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ews.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

ews/models.py
from django.db import models
from django.contrib.auth.models import User
from djgeojson.fields import PointField, PolygonField
# Create your models here.


class BathingSpot(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT, related_name="bathing_spots")
    name = models.CharField(max_length= 64)
    description = models.CharField(max_length = 200, default = " ")
    def __str__(self):
        return f"{self.name}"

class FeatureType(models.Model):
    name = models.CharField(max_length=64)
    unit = models.CharField(max_length=64, null = True)
    def __str__(self):
        return f"{self.name}"

class Site(models.Model):
    name = models.CharField(max_length=64, unique=True)
    ref_name =  models.CharField(max_length=64, null = True )
    geom = PointField(null = True)
    owner = models.ForeignKey(User, on_delete=models.PROTECT, related_name="owner")
    feature_type = models.ForeignKey(FeatureType, on_delete=models.CASCADE, related_name="feature_type")
    
    def __str__(self):
        return f"{self.name.replace('_', ' ').capitalize()}"
    
    @property
    def popupContent(self):
      return '<a href="/site_detail/{}"><strong>{}</strong></a> <p> {}</p>'.format(
          self.id,
          self.name.replace('_', ' ').capitalize(),
          self.feature_type)
    @property
    def SiteType(self):
        return '{}'.format(self.feature_type)
#"{% url 'ews:site_detail' entry.id  %}"

class Variable(models.Model):
    name = models.CharField(max_length=255, null = True)
    abbreviation = models.CharField(max_length=6, null = True)
    description = models.CharField(max_length=255, null = True)
    def __str__(self):
        return f"{self.name}"


class FeatureData(models.Model):
    date = models.DateTimeField()
    value = models.DecimalField(max_digits=1000, decimal_places=3)
    site = models.ForeignKey(Site, on_delete=models.CASCADE, related_name="site")
    variable = models.ForeignKey(Variable, on_delete=models.CASCADE, null=True, related_name="variable")
    class Meta:
        unique_together = ('date', 'site','value',)
    


class SelectArea(models.Model):
    name = models.CharField(max_length=64, unique=True)
    geom = PolygonField()
    feature_type = models.ForeignKey(FeatureType, on_delete=models.CASCADE, related_name = "areas")
    @property
    def SiteType(self):
        return '{}'.format(self.feature_type)
    def __str__(self):
            return f"{self.name}"

class PredictionModel(models.Model):
    name = models.CharField(max_length=64)
    user = models.ForeignKey(User, on_delete= models.CASCADE, related_name = "models")
    #bathing_spot = models.ForeignKey(BathingSpot, on_delete=models.CASCADE, related_name="models")
    site = models.ManyToManyField(Site, related_name = "models", null = True, blank = True)
    area = models.ManyToManyField(SelectArea, related_name = "models", null = True, blank = True)
    fit = models.BinaryField(null=True)
    predict = models.BooleanField(default= False)
    def __str__(self):
        return f"{self.name}"



#class MlModels(models.Model):

 #   model       =   models.BinaryField()

ews/forms.py
from ews.models import BathingSpot, Site, FeatureData, FeatureType, PredictionModel
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, ButtonHolder, Submit
from djgeojson.fields import PointField, MultiPolygonField

class BathingSpotForm(forms.ModelForm):
    class Meta:
        model = BathingSpot
        fields=[ "name", "description"]
        widgets={"description": forms.Textarea(attrs={'rows':4})}


class SiteForm(forms.ModelForm):
    class Meta:
        model = Site
        fields=["name", "feature_type"]


class FeatureDataForm(forms.ModelForm):
    class Meta:
        model = FeatureData
        fields=["date", "value", "site"]

class PredictionModelForm(forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        super(PredictionModelForm, self).__init__(*args, **kwargs)
        self.fields['area'].help_text = "Please selectthe areas you've created, which you want to use to model calibration"
        self.fields['site'].empty_label = None
        #self.fields['bathing_spot'].empty_label = None
        self.fields['site'].help_text = "Please select the bathing water for which you want to create a prediction model"
        self.fields['site'].queryset = Site.objects.filter(owner = user, feature_type__in= FeatureType.objects.filter(name = "BathingSpot"))
        #self.fields['bathing_spot'].queryset = BathingSpot.objects.filter(user = user)
        
        self.helper = FormHelper()
    class Meta:
        model =  PredictionModel
        fields=[ "site", "area","name"]
        widgets={"area": forms.CheckboxSelectMultiple()}




class PredictionModelForm2(forms.Form):
    name=forms.CharField(label="Enter a informative name")
    bathing_spot=forms.ModelChoiceField(queryset= BathingSpot.objects.all())
    rain_site = forms.ModelMultipleChoiceField(queryset=Site.objects.all())
    flow_site = forms.ModelMultipleChoiceField(queryset=Site.objects.all())

    def __init__(self, user, *args, **kwargs):
        super(PredictionModelForm2, self).__init__(*args, **kwargs)
        self.fields['rain_site'].queryset = Site.objects.filter(owner = user, feature_type = 1)
        self.fields['flow_site'].queryset = Site.objects.filter(owner = user, feature_type = 4)
        self.fields['bathing_spot'].queryset = BathingSpot.objects.filter(user = user)
        self.helper = FormHelper()

from leaflet.forms.widgets import LeafletWidget
from .models import SelectArea

class SelectAreaForm(forms.ModelForm):

    class Meta:
        model = SelectArea
        fields = ('name', 'geom', 'feature_type')
        widgets = {'geom': LeafletWidget()}

ews/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .forms import BathingSpotForm, SiteForm, FeatureDataForm, PredictionModelForm, SelectAreaForm
from .models import BathingSpot, Site, FeatureData, FeatureType, User, PredictionModel, SelectArea
from django.urls import reverse
from tablib import Dataset, core
from .resources import FeatureDataResource
from django.contrib.auth.decorators import login_required
import numpy as np
import pandas as  pd
from django.db import IntegrityError
import plotly.express as px
from plotly.offline import plot
from django_pandas.io import read_frame
# Create your views here.


@login_required
def bathingspots(request):
    entries = Site.objects.filter(owner = request.user, feature_type = FeatureType.objects.get(name = 'BathingSpot'))

    return render(request, "ews/index.html", {"entries": entries})

@login_required
def sites(request):
    sites = Site.objects.filter(owner = request.user)
    return render(request, "ews/sites.html", {"entries": sites})#,"item": "spot"})

@login_required(login_url="login")
def mlmodels(request):
    mlmodels = PredictionModel.objects.filter(user = request.user)
    return render(request, "ews/models.html", {"entries": mlmodels})

@login_required
def model_config(request):
    if request.method == "POST":
        form = PredictionModelForm(request.user, request.POST)
        if form.is_valid():
            pmodel = PredictionModel()
            pmodel.user = request.user
            pmodel.name = form.cleaned_data["name"]
            #pmodel.bathing_spot=form.cleaned_data["bathing_spot"]
            pmodel.save()
            pmodel.site.set(form.cleaned_data["site"])
            pmodel.area.set(form.cleaned_data["area"])
            pmodel.save()
            return HttpResponseRedirect(reverse("ews:mlmodels"))
        else:
            return HttpResponse(request, "Form not valid")

        return HttpResponseRedirect(reverse("ews:mlmodels"))
    else:
        pmodel_form = PredictionModelForm(request.user)
        return render(request, "ews/model_config.html", {"pmodel_form": pmodel_form})

def model_edit(request, model_id):
    model = PredictionModel.objects.get(id = model_id)
    return render(request, 'ews/sites.html', {"entries": model.site.all(), 'areas': model.area.all()})


@login_required
def spot_create(request):
    if request.method == "POST":
        form = BathingSpotForm(request.POST)
        user = request.user
        if form.is_valid():
            spot = BathingSpot()
            spot.name = form.cleaned_data["name"]
            spot.description = form.cleaned_data["description"]
            spot.user = user
            spot.save()
        return HttpResponseRedirect(reverse('ews:bathing_spots'))
    else:
        form = BathingSpotForm()          
    return render(request, "ews/create.html", {"form":form})




@login_required
def detail_view(request, spot_id):
    entries = BathingSpot.objects.get(id = spot_id)
   #sites = entries.sites.values()
    #featuretype = []
    
    #for i in range(len(sites)):
      #  sites[i]["feature_type"] = FeatureType.objects.get(id = sites[i]['feature_type_id'])
    
    return render(request, "ews/detail.html", {"entries": entries}) #, "sites":sites})


@login_required
def add_site(request):
    new_site = Site()
    if request.method == "POST":
        form = SiteForm(request.POST)
       # form.owner=request.user
        if form.is_valid():
            
            new_site.name=form.cleaned_data["name"]
            new_site.feature_type=form.cleaned_data["feature_type"]
            
            new_site.owner=request.user
            new_site.save()
            new_site.bathing_spot.set(form.cleaned_data["bathing_spot"])
            new_site.save()

        return HttpResponseRedirect(reverse('ews:sites'))
    else:
        # prepopulating with dictionary
        form = SiteForm()
        user_id = User.objects.filter(username=request.user).values()[0]["id"]
        spot= BathingSpot.objects.filter(user = user_id) 
    return render(request, "ews/add_site.html", {"form":form, "spot":spot})

def delete_site(request, site_id):
    Site.objects.get(id=site_id).delete()
    return HttpResponseRedirect(reverse('ews:sites'))

def delete_model(request, model_id):
    PredictionModel.objects.get(id=model_id).delete()
    return HttpResponseRedirect(reverse('ews:mlmodels'))




@login_required
def add_data(request):
    if request.method == "POST":
        form = FeatureDataForm(request.POST)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse('ews:add_site'))
    else:
        form = FeatureDataForm()
        
    return render(request, "ews/add_data.html", {"form":form})

#def delete_site(request, site_id):
#    site.objects.filter(id=site_id).delete()
 #   return render(request, )

#@login_required
@login_required
def file_upload(request, site_id):
    if request.method == 'POST':

        feature_resource = FeatureDataResource()
        dataset = Dataset()
        new_data = request.FILES['myfile']


        imported_data = dataset.load(new_data.read().decode("utf-8"), format="csv")
        #create an array containing the location_id
        location_arr = [site_id] * len(imported_data)

        # use the tablib API to add a new column, and insert the location array values
        imported_data.append_col(location_arr, header="site")

        try:
            result = feature_resource.import_data(dataset, dry_run=True)  # Test the data import
        except Exception as e:
            return HttpResponse(e, status=status.HTTP_400_BAD_REQUEST)

        if not result.has_errors():
            feature_resource.import_data(dataset, dry_run=False)  # Actually import now
        
        return HttpResponseRedirect(reverse("ews:site_detail",    args=[site_id,]))
    return render(request, 'ews/import.html', {"site_id":site_id})


@login_required
def site_detail(request, site_id):
        df = read_frame(FeatureData.objects.filter(site_id=site_id))
        entry = Site.objects.get(id = site_id)
        fig = px.bar(df, "date", "value",  opacity = 1)
        fig.update_traces(marker_color='rgb(158,202,225)', marker_line_color='rgb(8,48,107)',
                  marker_line_width=1.5, opacity=0.6)
        
        #fig.update_layout(title_text=df.site[0].replace("_", " "))
        fig = plot(fig, output_type = "div")
        
        return render(request, "ews/site_detail.html", {"fig":fig, "entry":entry})#, "data":df.to_html()})
    
@login_required
def selectarea_create(request):
    if request.method == "POST":
        form = SelectAreaForm(request.POST)
        if form.is_valid():
            selectarea = SelectArea()
            selectarea.name = form.cleaned_data["name"]
            selectarea.geom = form.cleaned_data["geom"]
            
            selectarea.feature_type = form.cleaned_data["feature_type"]
            selectarea.save()
            return HttpResponseRedirect(reverse("ews:selectarea_create"))
        else:
            return HttpResponse("Submission not successfull")
    else:
        form = SelectAreaForm()
        entries = Site.objects.all()
        areas = SelectArea.objects.all()
        return render(request, 'ews/selectarea_create.html', {'form': form, 'areas':areas, 'entries': entries})


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "ews/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "ews/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("ews:mlmodels"))
    else:
        return render(request, "ews/register.html")


import json
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from shapely.geometry import shape, Point
import statsmodels
from sklearn.model_selection import GridSearchCV, train_test_split
import pickle

def model_fit(request, model_id):
    model = PredictionModel.objects.get(id = model_id)
    areas = read_frame(model.area.all())
    areavars = []
    for index1, row1 in areas.iterrows():
        df = read_frame(Site.objects.filter(feature_type = FeatureType.objects.get(name=row1["feature_type"])))
        polygon = shape(row1["geom"])
        select = []
        
        for index2, row2 in df.iterrows():
            select.append(polygon.contains(shape(row2['geom'])))
        data = read_frame(FeatureData.objects.filter(site__in = df[select]['id']), index_col = "date")
        data["area"] = row1["name"]
        data["feature_type"] = row1["feature_type"]
        areavars.append(data)
    lagvars = []

    for i in range(len(areavars)):
        ft = areavars[i].area.unique()+ " " +areavars[i].feature_type.unique()
        d = areavars[i].pivot(columns = 'site', values = 'value')
        if len(d.columns) > 1:
            d = pd.DataFrame(d.mean(axis = 1, skipna = True))
        for j in [1, 2, 3, 4, 5]:
            df = pd.DataFrame()
            df[ft + '_shift_'+ str(j)] = d.rolling(window=j).mean().shift(1)
            lagvars.append(df)
            
    res = pd.concat(lagvars, axis = 1)
    res = res[res.index.month.isin([5, 6, 7, 8, 9])].reset_index()
    rain_cols = [col for col in res.columns if 'Rainfall' in col]

ews/templates/ews/add_data.html
{% extends "ews/base.html" %}

{% block body %}
    <h1>Create new data</h1>
    <h4>Here you can upload a single value</h4>
    <form method = "post", action="{% url 'ews:add_data'%}">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Submit">
    </form>
<hr>


<h4>Here you can upload a csv file containing multiple data</h4>

  <form method="post" enctype="multipart/form-data" action = "{%url 'ews:file_upload' %}">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>

{% endblock %}
  

ews/templates/ews/add_station.html
{% extends "ews/base.html" %}
{% load crispy_forms_tags %}
{% block body %}
    <div class="container" style="padding: 5%">

  <div class="row">
    <div class="col-sm-8">
    <h4>Create new predictor variable</h4>
    <form method = "post", action="{% url 'ews:add_station'%}">
        {% csrf_token %}
        {{form.name|as_crispy_field}}
        {{form.feature_type|as_crispy_field}}
        {{form.bathing_spot|as_crispy_field}}
        <input type="submit" value="Submit">
    </form>
    </div>
    <div class="col-sm-3 offset-sm-1"> <!--style= "background-color: #007c9f; color: white">--> 
     <h4 class= "mb-3">Options</h4>
        <a class = "btn btn-primary mt-3 btn-block" href="{% url "ews:spot_create" %}"> Create new bathing spot</a>
        <a class = "btn btn-primary mt-3 btn-block" href="{% url 'ews:add_station'%}"> Create new predictor</a>
        <a class = "btn btn-primary mt-3 btn-block" href = "{% url "ews:model_config" %}"> Configure prediction model </a>

    </div>
{% endblock %}

ews/templates/ews/base2.html
   <div class="col-sm-2"> <!--style= "background-color: #007c9f; color: white">--> 
       
        <h4 class= "mb-3">Create new items</h4>
           <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
           <li class="nav-item active">
               <a class = "nav-link text_link_kwb"  href="{% url "ews:spot_create" %}"> New bathing spot</a>
           </li>
           <li class="nav-item active">
                  <a class = "nav-link text_link_kwb"  href="{% url 'ews:add_site'%}"> New predictor</a>
           </li>
           <li class="nav-item active">
               <a class = "nav-link text_link_kwb" href = "{% url "ews:model_config" %}"> New prediction model </a>
           </li>
           </ul>
            
          </div>

ews/templates/ews/create.html
{% extends "ews/base.html" %}
{% load crispy_forms_tags %}

{% block body %}
    
    
 <div class="container" style="padding: 5%">

  <div class="row">
    <div class="col-sm-8">
    <h4>Create new bathing spot</h4>
      <form action = "{% url "ews:spot_create"%}", method = "post">
            {% csrf_token %}

            
            {{form|crispy}}
          <button class = "btn btn-primary" type = "submit">Submit</button>
        </form>
    
    </div>

    <div class="col-sm-3 offset-sm-1"> <!--style= "background-color: #007c9f; color: white">--> 
     <h4 class= "mb-3">Options</h4>
        <a class = "btn btn-primary mt-3 btn-block" href="{% url "ews:spot_create" %}"> Create new bathing spot</a>
        <a class = "btn btn-primary mt-3 btn-block" href="{% url 'ews:add_site'%}"> Create new predictor</a>
        <a class = "btn btn-primary mt-3 btn-block" href = "{% url "ews:model_config" %}"> Configure prediction model </a>

    </div>
{% endblock %}

ews/templates/ews/detail.html
{% extends "ews/base.html" %}

{% block title %}
{{entries.name}}
{% endblock %}

{% block body %}
    
    
 <div class="container" style="padding: 5%">

  <div class="row">
    <div class="col-sm-8">
     <h4>{{entries.name}}</h4>
     <hr>
     <p> {{entries.description}}

        <hr>
    
    <h5> Prediction models</h5>

    {%for site in sites%}
    <ul>
        
            <h5>{{site.name}}</h5> 
            <h5>{{site.id}}</h5> 
        
        <p>
            Type of predictor variable: {{site.feature_type}} 
            <button class= "btn-danger btn-sm">Delete</button>
            <form action="{% url 'ews:file_upload' site.id%}">
            <button class= "btn-primary btn-sm">Add data</button>
            </form>
        </p> 
        
    </ul>
        {% empty %}
        <p>There are currently no existing prediction models. Create some predictors and start modeling!</p>

        <a href="{% url 'ews:add_site' %}"></a>
        
        {% endfor %}
    </ul>

</div>



    <div class="col-sm-3 offset-sm-1"> <!--style= "background-color: #007c9f; color: white">--> 
     <h4 class= "mb-3">Options</h4>
        <a class = "btn btn-primary mt-3 btn-block" href="{% url "ews:spot_create" %}"> Create new bathing spot</a>
        <a class = "btn btn-primary mt-3 btn-block" href="{% url 'ews:add_site'%}"> Create new predictor</a>
        <a class = "btn btn-primary mt-3 btn-block" href = "{% url "ews:model_config" %}"> Configure prediction model </a>

    </div>
{% endblock %}

ews/templates/ews/import.html
{% extends "ews/base.html" %}
{% load crispy_forms_tags %}

{% block body %}

 <div class="container" style="padding: 5%">

  <div class="row">
    <div class="col-sm-8">
    <h4 class="mb-6">Upload your data as csv file</h4>

  
 <form  method="post" enctype="multipart/form-data" action = "{%url 'ews:file_upload' site_id%}">
    {% csrf_token %}
   <div class="custom-file mt-4" id="customFile" lang="en">
        <input type="file" class="custom-file-input" id="exampleInputFile" type="file" name="myfile" aria-describedby="fileHelp">
        <label class="custom-file-label" for="exampleInputFile">
           Select file...
        </label>
    </div>
   <button class = "btn btn-primary mt-3" type="submit">Upload</button>
  </form>
 <hr>
 <h5> Information/support</h5>
 With this for you are able to upload a file containing your time series data.


    </div>

    <div class="col-sm-3 offset-sm-1"> <!--style= "background-color: #007c9f; color: white">--> 
     <h4 class= "mb-3">Options</h4>
        <a class = "btn btn-primary mt-3 btn-block" href="{% url "ews:spot_create" %}"> Create new bathing spot</a>
        <a class = "btn btn-primary mt-3 btn-block" href="{% url 'ews:add_site'%}"> Create new predictor</a>
        <a class = "btn btn-primary mt-3 btn-block" href = "{% url "ews:model_config" %}"> Configure prediction model </a>

    </div>

{% endblock %}


  

ews/templates/ews/index.html
{% extends "ews/base.html" %}

{% block title %}
    
{% endblock %}

{% block body %}
<div class="container" style="padding: 5%">

  <div class="row">
    <div class="col-sm-8">
   
    <ul>
        {% for entry in entries %}
     <div class="media px-3 mt-3">
              <div class="media-left pr-3">
             <a href= "{% url 'ews:detail' entry.id %}" > 
              <img class= "img-fluid" src="/static/ews/img/placeholder_dwc.png" alt="...">
            </a>
        </div>
        <div class="media-body">
                  <h4 class="media-heading">{{entry.name|title}}</h4>
                   <!--<p> {{entry.description|capfirst}} --> 
                   <a href= "{% url 'ews:detail' entry.id %}", class = "btn-sm btn-primary sm"> Edit </a>
                   <a href= "{% url 'ews:detail' entry.id %}", class = "btn-sm btn-danger sm"> Delete </a>
                </div>
        </div>
        {% empty %}
        <p>No Bathing spot there, yet. Create one and start modeling!</p>
        {% endfor %}
        
    </ul>
    </div>

    <div class="col-sm-3 offset-sm-1"> <!--style= "background-color: #007c9f; color: white">--> 
     <h4 class= "mb-3">Options</h4>
        <a class = "btn btn-primary mt-3 btn-block" href="{% url "ews:spot_create" %}"> Create new bathing spot</a>
        <a class = "btn btn-primary mt-3 btn-block" href="{% url 'ews:add_site'%}"> Create new predictor</a>
        <a class = "btn btn-primary mt-3 btn-block" href = "{% url "ews:model_config" %}"> Configure prediction model </a>

    </div>
{% endblock %}




            

ews/templates/ews/models.html
{% extends "ews/base.html" %}

{% block title %}
    
{% endblock %}

{% block body %}
<div class="container" style="padding: 5%">

  <div class="row">
    <div class="col-sm-8">
   
    <ul>
        {% for entry in entries %}
     <div class="media px-3 mt-3">
              <div class="media-left pr-3">
              <!-- <a href= "{% url 'ews:detail' entry.id %}" > -->
              <img class= "img-fluid" src="/static/ews/img/placeholder_dwc.png" alt="...">
            </a>
        </div>

        <div class="media-body">
                  <h4 class="media-heading">{{entry.name|title}}</h4>
                   <p> {{entry.description|capfirst}} 
                   <a href= "{% url 'ews:model_fit' entry.id %}", class = "btn-sm btn-primary sm"> Fit model </a>
                   <a href= "{% url 'ews:model_edit' entry.id %}", class = "btn-sm btn-danger sm"> Edit config </a>
                </div>
        </div>
        {% empty %}
        <p>No Prediction models calibrated, yet. Click on <strong>configure prediction model</strong> to create one!</p>
        {% endfor %}
        
    </ul>
    </div>

    <div class="col-sm-3 offset-sm-1"> <!--style= "background-color: #007c9f; color: white">--> 
     <h4 class= "mb-3">Options</h4>
        <a class = "btn btn-primary mt-3 btn-block" href="{% url "ews:spot_create" %}"> Create new bathing spot</a>
        <a class = "btn btn-primary mt-3 btn-block" href="{% url 'ews:add_site'%}"> Create new predictor</a>
        <a class = "btn btn-primary mt-3 btn-block" href = "{% url "ews:model_config" %}"> Configure prediction model </a>

    </div>
{% endblock %}




            

ews/templates/ews/site_detail.html
{% extends "ews/base.html" %}

{% block body %}
<div class="container" style="padding: 5%">
  <h4 class="media-heading">{{entry.name|title}}</h4>
  <span><a href= "{% url 'ews:file_upload' entry.id  %}", class = "btn-sm btn-primary sm"> Add data </a>
  <a href= "{% url 'ews:delete_site' entry.id  %}", class = "btn-sm btn-danger sm"> Delete </a>
  </span>
  <div class="row">
    <div class="col-sm-8">
   
  <div id="hero-graph">
              {% autoescape off %}
              {{ fig }}
              {% endautoescape %}

</div>

  <div class="media-body">
           
             <p> {{entry.description|capfirst}} 
  </div>

<div class="table-responsive table-body">
    <div class="table table-hover" style = "width:100%;">
      {{data|safe}}
    </div>
</div>
</div>




    <div class="col-sm-3 offset-sm-1"> <!--style= "background-color: #007c9f; color: white">--> 
     <h4 class= "mb-3">Options</h4>
        <a class = "btn btn-primary mt-3 btn-block" href="{% url "ews:spot_create" %}"> Create new bathing spot</a>
        <a class = "btn btn-primary mt-3 btn-block" href="{% url 'ews:add_site'%}"> Create new predictor</a>
        <a class = "btn btn-primary mt-3 btn-block" href = "{% url "ews:model_config" %}"> Configure prediction model </a>

    </div>
{% endblock %}
  